In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(threshold=np.inf)


In [2]:
def show(image):
    cv2.imshow("Image", image)
    cv2.waitKey(3000)
    cv2.destroyAllWindows()

In [3]:
def save(image, name):
    cv2.imwrite(name, image)

In [4]:
image_path = "D:\Assignment 1\Q3\\test\\3_c.png"
image= cv2.imread(image_path)
if image is None:
    print("Error: Unable to load image.")
show(image)


In [5]:
# gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# # show(gray)
# # save(gray,"gray")
# # cv2.imwrite("pic", gray)
# blur = cv2.GaussianBlur(image, (9, 9), 30)
# blur = cv2.GaussianBlur(blur, (9, 9), 30)
# blur = cv2.GaussianBlur(blur, (15, 15), 100)
# blur = cv2.blur(blur, (5,5))
# blur = cv2.blur(blur, (5,5))
# show(blur)


In [6]:
# # kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
# kernel = np.array([[-1,-1,-1],[-1,9,-1],[-1,-1,-1]])
# sh_im = cv2.filter2D(blur, ddepth = -1, kernel = kernel)
# show(sh_im)

In [7]:
thresh = cv2.cvtColor(sh_im, cv2.COLOR_BGR2GRAY)

thresh = cv2.threshold(thresh, 200, 255, cv2.THRESH_BINARY)[1]


In [8]:
# np.shape(thresh)

(200, 235)

In [9]:
# erosion_size = 1
# element = cv2.getStructuringElement(cv2.MORPH_RECT, (2 * erosion_size + 1, 2 * erosion_size + 1), (erosion_size, erosion_size) )
# thresh = cv2.erode(thresh, element)
# show(thresh)

In [10]:
edges = cv2.Canny(thresh, threshold1=50, threshold2=150)
show(edges)

In [11]:
show(gray)
blurred = cv2.GaussianBlur(gray, (5, 5), 0)
save(blurred,'blur.jpg')
thresh = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY)[1]
show(thresh)
save(thresh,'thrsh_test.jpg')
lines = cv2.HoughLinesP(thresh, 1, np.pi / 180, threshold=200, minLineLength=10, maxLineGap=0)
print(lines)


line_image = np.copy(image)
if lines is not None:
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(line_image, (x1, y1), (x2, y2), (0, 0, 255), 2)  # Red lines
show(line_image)

[[[137 107 229 199]]

 [[ 69 121 190   0]]

 [[109  83 127 101]]

 [[ 79 142 187  34]]

 [[ 11   0  90  79]]

 [[  1   0  86  85]]

 [[ 35   0 100  65]]

 [[ 33   0  98  65]]

 [[147 115 234  28]]

 [[  0   1  85  86]]

 [[118 123 194 199]]

 [[124 119 204 199]]

 [[  0   8  78  86]]

 [[ 43   0 111  68]]

 [[ 26   0 107  81]]

 [[132 125 234  23]]

 [[ 48 169 103 114]]

 [[112 128 183 199]]

 [[ 55 199 118 136]]

 [[131 113 217 199]]

 [[133 111 221 199]]

 [[116  70 186   0]]

 [[111 112 223   0]]

 [[158 101 234 177]]

 [[ 79 114 193   0]]

 [[127  69 196   0]]

 [[130 114 215 199]]

 [[  0  19  73  92]]

 [[145  83 228   0]]

 [[184  66 234  16]]

 [[149 110 234 195]]

 [[134 125 208 199]]

 [[ 53   0 112  59]]

 [[ 70 199 131 138]]

 [[157 107 234 184]]

 [[188  26 214   0]]

 [[131  67 145  81]]

 [[  0  11  75  86]]

 [[ 47   0 106  59]]

 [[143 132 156 119]]

 [[ 49 199 115 133]]

 [[109  90 119  80]]

 [[165 106 234  37]]

 [[108 148 159 199]]

 [[  0  29  70  99]]

 [[  0  33

In [12]:
show(image)

In [13]:
line_angles = []
for line in lines:
    rho, theta = line[0]
    angle_deg = theta * 180 / np.pi
    line_angles.append(angle_deg)
    
print(line_angles)

ValueError: too many values to unpack (expected 2)

In [ ]:
for line in lines:
    rho, theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(image, (x1, y1), (x2, y2), (0, 0, 255), 2)
show(image)

In [ ]:
# valid_lines = []

# # Calculate angles and lengths of detected lines and store valid lines
# for line in lines:
#     rho, theta = line[0]
#     angle_deg = theta * 180 / np.pi
    
#     # Convert polar coordinates to Cartesian coordinates
#     a = np.cos(theta)
#     b = np.sin(theta)
#     x0 = a * rho
#     y0 = b * rho
#     x1 = int(x0 + 1000 * (-b))
#     y1 = int(y0 + 1000 * (a))
#     x2 = int(x0 - 1000 * (-b))
#     y2 = int(y0 - 1000 * (a))
    
#     # Calculate the length of the line
#     line_length = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    
#     # Filter lines longer than 10 pixels
#     if line_length > 10:
#         valid_lines.append((angle_deg, line_length))

# # Sort valid lines by length in descending order
# valid_lines.sort(key=lambda x: x[1], reverse=True)

# # Display the valid lines
# for angle_deg, line_length in valid_lines:
#     print(f"Angle: {angle_deg:.2f} degrees, Length: {line_length:.2f} pixels")

Angle: 90.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 2000.00 pixels
Angle: 0.00 degrees, Length: 20

In [ ]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
show(gray)
print(np.shape(gray))


(200, 235)


In [ ]:
sobel_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
sobel_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)

# Calculate the absolute gradients
abs_sobel_x = np.absolute(sobel_x)
abs_sobel_y = np.absolute(sobel_y)

# Combine the gradient images
gradient = cv2.addWeighted(abs_sobel_x, 0.5, abs_sobel_y, 0.5, 0)

# Threshold the gradient to create a binary edge map
threshold_value = 50  # Adjust this threshold as needed
edge_map = cv2.threshold(gradient, threshold_value, 255, cv2.THRESH_BINARY)[1]
show(edge_map)


In [ ]:
h, theta, d = cv2.HoughLines(edge_map)
accum, angles, dists = cv2.HoughLinesPointSet(h, theta, d)
angle = np.rad2deg(np.mode(angles)[0][0])

if (angle < 0):

    angle = angle + 90

else:

    angle = angle - 90

print(angle)

error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'HoughLines'
> Overload resolution failed:
>  - HoughLines() missing required argument 'rho' (pos 2)
>  - HoughLines() missing required argument 'rho' (pos 2)
